version: '3.8'

services:
  db:
    image: mariadb
    restart: always
    environment:
      MARIADB_ROOT_PASSWORD: squad01
    volumes:
      - ./data:/var/lib/mariadb

  adminer:
    image: adminer
    restart: always
    ports:
      - 8181:8080