  # services:
  #   maria-db:
  #     image: mariadb:latest
  #     container_name: maria-db
  #     restart: always
  #     environment:
  #       MYSQL_ROOT_PASSWORD: admin
  #       MYSQL_DATABASE: copaldb
  #       MYSQL_USER: root
  #       MYSQL_PASSWORD: squad01
  #     volumes:
  #       - data:/var/lib/mysql
  #     ports:
  #       - "3306:3306"
# Use root/example as user/password credentials
version: '3.1'

services:

  db:
    image: mariadb
    restart: always
    environment:
      MARIADB_ROOT_PASSWORD: example

  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080
