version: '3.8'

services:
  db:
    image: mariadb
    restart: always
    environment:
      MARIADB_ROOT_PASSWORD: squad01
      MYSQL_ROOT_HOST: 172.18.0.1
    command: --init-file /data/app/init.sql
    volumes:
      - ./data:/var/lib/mariadb
      - ./init.sql:/data/app/init.sql

    ports:
      - 3306:3306

  web:
    build: .
    depends_on:
      - db
    ports:
      - "8080:8080"
    environment:
      SPRING_APPLICATION_JSON: '{
        "spring.datasource.url": "jdbc:mariadb://db:3306/dev",
        "spring.datasource.username": "root",
        "spring.datasource.password": "squad01",
        "spring.datasource.driver-class-name": "org.mariadb.jdbc.Driver",
        "spring.jpa.properties.hibernate.dialect": "org.hibernate.dialect.MariaDBDialect",
        "spring.jpa.hibernate.ddl-auto": "create",
        "spring.datasource.hikari.connection-timeout": "20000",
        "spring.datasource.hikari.driver-class-name": "org.mariadb.jdbc.Driver",
        "spring.datasource.hikari.maximum-pool-size": 5,
        "spring.data.jpa.repositories.enabled": true,
        "spring.jpa.show-sql": true
      }'
